services:
  #service 1: definition of mysql database
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_manage
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3307"
    restart: always
  # service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root