version: "3.9"
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_manage
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3307
    restart: always
    networks:
      - employee_network
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-spring-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  employee_network: